export const categories = [
  {
    id: "ai-tools",
    slug: "ai-tools",
    name: "AI Tools",
    description: "Extensions powered by artificial intelligence",
    icon: "Bot",
    color: "#6366f1",
    gradient: "from-violet-500 to-indigo-500",
  },
  {
    id: "productivity",
    slug: "productivity",
    name: "Productivity",
    description: "Get more done with powerful productivity extensions",
    icon: "Zap",
    color: "#f59e0b",
    gradient: "from-amber-500 to-orange-500",
  },
  {
    id: "privacy-security",
    slug: "privacy-security",
    name: "Privacy & Security",
    description: "Stay safe and protect your data online",
    icon: "Shield",
    color: "#10b981",
    gradient: "from-emerald-500 to-teal-500",
  },
  {
    id: "developer-tools",
    slug: "developer-tools",
    name: "Developer Tools",
    description: "Essential tools for web developers",
    icon: "Code2",
    color: "#3b82f6",
    gradient: "from-blue-500 to-cyan-500",
  },
  {
    id: "writing",
    slug: "writing",
    name: "Writing",
    description: "Grammar checkers, note-taking, and writing assistants",
    icon: "PenLine",
    color: "#8b5cf6",
    gradient: "from-purple-500 to-pink-500",
  },
  {
    id: "design",
    slug: "design",
    name: "Design",
    description: "Color pickers, screen capture, and design utilities",
    icon: "Palette",
    color: "#ec4899",
    gradient: "from-pink-500 to-rose-500",
  },
  {
    id: "shopping",
    slug: "shopping",
    name: "Shopping",
    description: "Find the best deals and save money online",
    icon: "ShoppingBag",
    color: "#f97316",
    gradient: "from-orange-500 to-red-500",
  },
  {
    id: "news-reading",
    slug: "news-reading",
    name: "News & Reading",
    description: "Read later, summarize, and stay informed",
    icon: "Newspaper",
    color: "#14b8a6",
    gradient: "from-teal-500 to-cyan-500",
  },
  {
    id: "research-learning",
    slug: "research-learning",
    name: "Research & Learning",
    description: "AI tools for academic research, paper analysis, summaries, and studying",
    icon: "GraduationCap",
    color: "#06b6d4",
    gradient: "from-cyan-500 to-blue-500",
  },
  {
    id: "content-creator",
    slug: "content-creator",
    name: "Content Creator",
    description: "AI design, presentation, and media tools for digital marketers",
    icon: "Video",
    color: "#f43f5e",
    gradient: "from-rose-500 to-pink-500",
  },
  {
    id: "freelancer-toolkit",
    slug: "freelancer-toolkit",
    name: "Freelancer Toolkit",
    description: "Screen recorders, web clippers, and tracking tools for remote workers",
    icon: "Briefcase",
    color: "#8b5cf6",
    gradient: "from-purple-500 to-violet-500",
  },
  {
    id: "seo-marketing",
    slug: "seo-marketing",
    name: "SEO & Marketing",
    description: "Keyword metrics, competitor analytics, and SEO audits for bloggers",
    icon: "BarChart3",
    color: "#f59e0b",
    gradient: "from-amber-500 to-yellow-500",
  },
] as const;

export type Category = (typeof categories)[number];
export type CategorySlug = Category["slug"];
