export const categories = [
  {
    id: "ai-tools",
    slug: "ai-tools",
    name: "AI Tools",
    description: "Extensions powered by artificial intelligence",
    icon: "Bot",
    color: "#6366f1",
    gradient: "from-violet-500 to-indigo-500",
  },
  {
    id: "productivity",
    slug: "productivity",
    name: "Productivity",
    description: "Get more done with powerful productivity extensions",
    icon: "Zap",
    color: "#f59e0b",
    gradient: "from-amber-500 to-orange-500",
  },
  {
    id: "privacy-security",
    slug: "privacy-security",
    name: "Privacy & Security",
    description: "Stay safe and protect your data online",
    icon: "Shield",
    color: "#10b981",
    gradient: "from-emerald-500 to-teal-500",
  },
  {
    id: "developer-tools",
    slug: "developer-tools",
    name: "Developer Tools",
    description: "Essential tools for web developers",
    icon: "Code2",
    color: "#3b82f6",
    gradient: "from-blue-500 to-cyan-500",
  },
  {
    id: "writing",
    slug: "writing",
    name: "Writing",
    description: "Grammar checkers, note-taking, and writing assistants",
    icon: "PenLine",
    color: "#8b5cf6",
    gradient: "from-purple-500 to-pink-500",
  },
  {
    id: "design",
    slug: "design",
    name: "Design",
    description: "Color pickers, screen capture, and design utilities",
    icon: "Palette",
    color: "#ec4899",
    gradient: "from-pink-500 to-rose-500",
  },
  {
    id: "shopping",
    slug: "shopping",
    name: "Shopping",
    description: "Find the best deals and save money online",
    icon: "ShoppingBag",
    color: "#f97316",
    gradient: "from-orange-500 to-red-500",
  },
  {
    id: "news-reading",
    slug: "news-reading",
    name: "News & Reading",
    description: "Read later, summarize, and stay informed",
    icon: "Newspaper",
    color: "#14b8a6",
    gradient: "from-teal-500 to-cyan-500",
  },
] as const;

export type Category = (typeof categories)[number];
export type CategorySlug = Category["slug"];
