import { Extension, ExtensionWithDetails } from "@/types/extension";
import { Review } from "@/types/review";

export interface MockBlogPost {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  coverImageUrl: string;
  category: string;
  tags: string[];
  readingTimeMinutes: number;
  publishedAt: string;
  isFeatured?: boolean;
}

export const mockExtensions: ExtensionWithDetails[] = [
  {
    id: "ext-1",
    slug: "chatgpt-sidebar",
    chromeStoreId: "chatgpt-sidebar-id",
    name: "ChatGPT Sidebar & File Uploader",
    tagline: "Access ChatGPT 4o, Claude 3.5, and Gemini Pro instantly in any tab. Upload large PDF & doc files directly.",
    description: "Unleash the power of AI side-by-side with your browsing. ChatGPT Sidebar integrates advanced model capabilities directly into your browser side panel. Summarize articles, explain complex code, draft emails, and translate pages on the fly. Version 2.4 adds direct file uploads (PDFs, DOCX, CSV) and automatic OCR capabilities for images. Designed for developers, researchers, and content creators looking to double their efficiency.",
    logoUrl: "🤖",
    websiteUrl: "https://chatgptsidebar.io",
    chromeStoreUrl: "https://chromewebstore.google.com",
    affiliateUrl: "https://chatgptsidebar.io/ref=roketdev",
    status: "featured",
    isFeatured: true,
    isSponsored: false,
    categoryId: "ai-tools",
    categorySlug: "ai-tools",
    categoryName: "AI Tools",
    version: "2.4.2",
    totalUsers: 245000,
    weeklyUsers: 42000,
    avgRating: 4.85,
    totalReviews: 1420,
    totalInstalls: 98000,
    clickCount: 12450,
    metaTitle: "ChatGPT Sidebar - Chrome AI Assistant Extension",
    metaDescription: "Access ChatGPT, Claude, and Gemini in any tab. PDF parser and AI helper in your sidebar.",
    tags: ["AI", "Productivity", "ChatGPT", "Claude", "File Parser"],
    permissions: ["sidePanel", "activeTab", "storage"],
    pricingType: "freemium",
    price: 9.99,
    trustBadge: "Best For Developers",
    createdAt: "2025-01-15T00:00:00Z",
    updatedAt: "2026-05-20T00:00:00Z",
    screenshots: [
      { id: "s1-1", extensionId: "ext-1", url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=60", altText: "Sidebar interface inside Google Search", sortOrder: 0 },
      { id: "s1-2", extensionId: "ext-1", url: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&auto=format&fit=crop&q=60", altText: "AI File Uploader panel parsing document", sortOrder: 1 },
      { id: "s1-3", extensionId: "ext-1", url: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&auto=format&fit=crop&q=60", altText: "Instant translator settings screen", sortOrder: 2 }
    ]
  },
  {
    id: "ext-2",
    slug: "monica-ai",
    chromeStoreId: "monica-ai-id",
    name: "Monica: Your AI Copilot",
    tagline: "Chat with GPT-4, Claude 3.5, and Gemini. Write, translate, and capture web pages easily.",
    description: "Monica is your all-in-one AI assistant, equipped with advanced LLMs (GPT-4, Claude 3.5, Gemini). Press Cmd+M or Ctrl+M to chat with Monica, draft blogs, summarize articles, translate PDFs, or search the web with instant AI insights. Perfect for content creators and professionals looking to double their workflow speed.",
    logoUrl: "🧠",
    websiteUrl: "https://monica.im",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "approved",
    isFeatured: true,
    isSponsored: false,
    categoryId: "ai-tools",
    categorySlug: "ai-tools",
    categoryName: "AI Tools",
    version: "5.6.2",
    totalUsers: 3000000,
    weeklyUsers: 450000,
    avgRating: 4.82,
    totalReviews: 14500,
    totalInstalls: 980000,
    clickCount: 18520,
    metaTitle: "Monica AI Chrome Extension - Your AI Copilot",
    metaDescription: "All-in-one AI copilot extension. GPT-4, Claude, Gemini, and image search inside Monica.",
    tags: ["AI Assistant", "GPT-4", "Claude", "Writing", "Copilot"],
    permissions: ["activeTab", "storage", "contextMenus"],
    pricingType: "freemium",
    price: 15.00,
    trustBadge: "Editor Approved",
    createdAt: "2023-04-12T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
    screenshots: [
      { id: "s2-1", extensionId: "ext-2", url: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&auto=format&fit=crop&q=60", altText: "Monica chat sidebar assistant", sortOrder: 0 },
      { id: "s2-2", extensionId: "ext-2", url: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop&q=60", altText: "AI writing copilot prompt panel", sortOrder: 1 }
    ]
  },
  {
    id: "ext-3",
    slug: "perplexity-ai",
    chromeStoreId: "perplexity-id",
    name: "Perplexity: AI Search Companion",
    tagline: "Get instant, fully cited answers to any search query directly inside your browser window.",
    description: "Perplexity AI replaces traditional search with instant, interactive, and fully cited answers. Highlight any text or ask a question directly. Perplexity searches the live web, outlines the best resources, and synthesizes clean answers with source citations. Indispensable for research, programming, and learning.",
    logoUrl: "🔍",
    websiteUrl: "https://perplexity.ai",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "approved",
    isFeatured: true,
    isSponsored: false,
    categoryId: "research-learning",
    categorySlug: "research-learning",
    categoryName: "Research & Learning",
    version: "1.2.0",
    totalUsers: 1500000,
    weeklyUsers: 280000,
    avgRating: 4.88,
    totalReviews: 8900,
    totalInstalls: 540000,
    clickCount: 22410,
    metaTitle: "Perplexity AI Chrome Extension - Conversational Search",
    metaDescription: "AI search companion by Perplexity. Instant web searching, summaries, and citations.",
    tags: ["AI Search", "Research", "Citations", "Knowledge", "Perplexity"],
    permissions: ["tabs", "storage"],
    pricingType: "free",
    trustBadge: "Best For Research",
    createdAt: "2024-02-18T00:00:00Z",
    updatedAt: "2026-05-10T00:00:00Z",
    screenshots: [
      { id: "s3-1", extensionId: "ext-3", url: "https://images.unsplash.com/photo-1546074177-ffedd79d424c?w=800&auto=format&fit=crop&q=60", altText: "Instant citation and answers panel", sortOrder: 0 }
    ]
  },
  {
    id: "ext-4",
    slug: "merlin-ai",
    chromeStoreId: "merlin-id",
    name: "Merlin: ChatGPT Assistant & YouTube Summarizer",
    tagline: "Summarize YouTube videos, write LinkedIn posts, and draft Gmail replies instantly with AI.",
    description: "Merlin is your custom ChatGPT Chrome assistant. With Merlin, you can summarize lengthy YouTube videos in one click, draft high-converting LinkedIn posts, write professional email replies on Gmail, and get GPT-4 responses alongside Google Search. A massive time-saver for marketers, sales, and creators.",
    logoUrl: "🧙‍♂️",
    websiteUrl: "https://getmerlin.in",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "featured",
    isFeatured: true,
    isSponsored: false,
    categoryId: "ai-tools",
    categorySlug: "ai-tools",
    categoryName: "AI Tools",
    version: "4.8.0",
    totalUsers: 2000000,
    weeklyUsers: 350000,
    avgRating: 4.78,
    totalReviews: 12500,
    totalInstalls: 880000,
    clickCount: 16120,
    metaTitle: "Merlin AI Chrome Extension - ChatGPT Web Assistant",
    metaDescription: "ChatGPT assistant Merlin. Summarize YouTube, LinkedIn writer, and Gmail drafter.",
    tags: ["ChatGPT", "YouTube Summary", "LinkedIn Writer", "Gmail Assister", "Marketing"],
    permissions: ["activeTab", "storage", "contextMenus"],
    pricingType: "freemium",
    price: 19.00,
    trustBadge: "Community Favorite",
    createdAt: "2023-09-01T00:00:00Z",
    updatedAt: "2026-05-28T00:00:00Z",
    screenshots: [
      { id: "s4-1", extensionId: "ext-4", url: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&auto=format&fit=crop&q=60", altText: "Merlin YouTube summarizer panel", sortOrder: 0 }
    ]
  },
  {
    id: "ext-5",
    slug: "sider-ai",
    chromeStoreId: "sider-id",
    name: "Sider: AI Sidebar & Translation",
    tagline: "Your AI sidekick for reading, writing, and coding. Translate and explain logic in any web tab.",
    description: "Sider is a smart browser sidebar designed to assist you with daily reading, writing, and programming. It supports GPT-4, Claude, and Gemini to explain complex code blocks, check grammar mistakes, draft text, and provide high-accuracy language translations. Excellent companion for developers and writers.",
    logoUrl: "✨",
    websiteUrl: "https://sider.ai",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "approved",
    isFeatured: true,
    isSponsored: false,
    categoryId: "ai-tools",
    categorySlug: "ai-tools",
    categoryName: "AI Tools",
    version: "4.24.0",
    totalUsers: 4000000,
    weeklyUsers: 650000,
    avgRating: 4.86,
    totalReviews: 26000,
    totalInstalls: 1500000,
    clickCount: 29820,
    metaTitle: "Sider AI Sidebar Chrome Extension",
    metaDescription: "AI Sidebar Sider. GPT-4, Claude, and Gemini translator and explainer on any website.",
    tags: ["AI Sidebar", "Translation", "Code Explainer", "Writing Assistant", "Claude"],
    permissions: ["sidePanel", "activeTab", "storage"],
    pricingType: "freemium",
    price: 10.00,
    trustBadge: "Trending This Week",
    createdAt: "2023-05-20T00:00:00Z",
    updatedAt: "2026-06-03T00:00:00Z",
    screenshots: [
      { id: "s5-1", extensionId: "ext-5", url: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=60", altText: "Sider sidebar showing code explanation", sortOrder: 0 }
    ]
  },
  {
    id: "ext-6",
    slug: "max-ai",
    chromeStoreId: "maxai-id",
    name: "MaxAI.me: Use 1-Click AI Anywhere",
    tagline: "Rewrite, summarize, reply, and translate text instantly on any website with GPT-4 and Claude.",
    description: "MaxAI.me brings 1-click generative AI directly into your browsing cursor. Highlight any text on any website to rewrite, summarize, check grammar, translate, or reply instantly. It supports OpenAI GPT-4, Anthropic Claude 3, and Google Gemini. Perfect for accelerating emails, documents, and social reading.",
    logoUrl: "🚀",
    websiteUrl: "https://maxai.me",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "approved",
    isFeatured: true,
    isSponsored: false,
    categoryId: "ai-tools",
    categorySlug: "ai-tools",
    categoryName: "AI Tools",
    version: "3.2.4",
    totalUsers: 2500000,
    weeklyUsers: 380000,
    avgRating: 4.81,
    totalReviews: 12450,
    totalInstalls: 920000,
    clickCount: 14210,
    metaTitle: "MaxAI.me Chrome Extension - 1-Click AI Helper",
    metaDescription: "Highlight text to write, summarize, and translate instantly. Powered by GPT-4 and Claude.",
    tags: ["1-Click AI", "Rewrite", "Grammar Checker", "SaaS Productivity", "Gemini"],
    permissions: ["activeTab", "storage", "contextMenus"],
    pricingType: "freemium",
    price: 24.00,
    trustBadge: "Best For Productivity",
    createdAt: "2023-11-04T00:00:00Z",
    updatedAt: "2026-04-12T00:00:00Z",
    screenshots: [
      { id: "s6-1", extensionId: "ext-6", url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=60", altText: "MaxAI 1-click prompt window next to highlighted text", sortOrder: 0 }
    ]
  },
  {
    id: "ext-7",
    slug: "octotree-github-code-tree",
    chromeStoreId: "octotree-id",
    name: "Octotree: GitHub Code Tree",
    tagline: "GitHub on steroids. Visual file tree for fast repository browsing and code reviews.",
    description: "Browser extension that enhances GitHub repository browsing. It displays a fast, interactive sidebar folder tree that lets developers browse source codes, search files, and check merge requests without constant page reloads. Trusted by over 1 million software developers.",
    logoUrl: "🌲",
    websiteUrl: "https://octotree.io",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "approved",
    isFeatured: true,
    isSponsored: false,
    categoryId: "developer-tools",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    version: "8.3.1",
    totalUsers: 1200000,
    weeklyUsers: 210000,
    avgRating: 4.81,
    totalReviews: 3400,
    totalInstalls: 450000,
    clickCount: 11200,
    metaTitle: "Octotree Chrome Extension - GitHub File Browser",
    metaDescription: "Visual file tree sidebar for GitHub repository navigation. Explores source code structures easily.",
    tags: ["GitHub", "DevTools", "Code Browser", "Repository"],
    permissions: ["tabs", "storage", "declarativeContent"],
    pricingType: "freemium",
    price: 4.99,
    trustBadge: "Best For Developers",
    createdAt: "2020-04-12T00:00:00Z",
    updatedAt: "2026-05-18T00:00:00Z",
    screenshots: [
      { id: "s7-1", extensionId: "ext-7", url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=60", altText: "Octotree folder tree panel inside GitHub repository screen", sortOrder: 0 }
    ]
  },
  {
    id: "ext-8",
    slug: "daily-dev-news-aggregator",
    chromeStoreId: "dailydev-id",
    name: "daily.dev: Developer News",
    tagline: "The easiest way to stay updated on tech news. Curated feeds for software engineers.",
    description: "Upgrade your new tab browser screen to a personalized, highly curated news reader. It aggregates engineering posts, tutorials, release updates, and developer guides from hundreds of major tech portals (Medium, Hacker News, Dev.to, GitHub). Customizable tags and zero-tracking privacy settings.",
    logoUrl: "🔥",
    websiteUrl: "https://daily.dev",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "featured",
    isFeatured: true,
    isSponsored: false,
    categoryId: "productivity",
    categorySlug: "productivity",
    categoryName: "Productivity",
    version: "3.14.0",
    totalUsers: 900000,
    weeklyUsers: 180000,
    avgRating: 4.88,
    totalReviews: 2900,
    totalInstalls: 320000,
    clickCount: 9500,
    metaTitle: "daily.dev Chrome Extension - Tech News Aggregator",
    metaDescription: "Read the best software developer blogs, engineering releases, and tech trends in your new tab.",
    tags: ["News", "Productivity", "Blogs", "Tech Feeds"],
    permissions: ["storage", "alarms"],
    pricingType: "free",
    trustBadge: "Trending This Week",
    createdAt: "2021-09-05T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
    screenshots: [
      { id: "s8-1", extensionId: "ext-8", url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=60", altText: "daily.dev new tab feed dashboard with tech articles", sortOrder: 0 }
    ]
  },
  {
    id: "ext-9",
    slug: "clear-cache-dev",
    chromeStoreId: "clearcache-id",
    name: "Clear Cache: One-Click Cleaner",
    tagline: "Clear browser cookies, storage, cache, and history with a single click.",
    description: "A lightweight utility tool designed for web developers. Instantly clears app caches, active cookie files, HTML5 local storage, database files, and downloads with one click from the browser toolbar. Fully configurable to keep specific cookie sessions while purging others.",
    logoUrl: "🧹",
    websiteUrl: "https://clear-cache.io",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "approved",
    isFeatured: false,
    isSponsored: false,
    categoryId: "developer-tools",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    version: "2.1.4",
    totalUsers: 3000000,
    weeklyUsers: 400000,
    avgRating: 4.75,
    totalReviews: 1200,
    totalInstalls: 1500000,
    clickCount: 5400,
    metaTitle: "Clear Cache Dev Extension - One Click Cookies Cleaner",
    metaDescription: "Purge web browsing files, store items, local storage databases, and caches in 1-click.",
    tags: ["Cache", "DevTools", "Clear Cache", "Storage"],
    permissions: ["browsingData", "storage"],
    pricingType: "free",
    trustBadge: "Best For Developers",
    createdAt: "2017-02-14T00:00:00Z",
    updatedAt: "2026-04-20T00:00:00Z",
    screenshots: [
      { id: "s9-1", extensionId: "ext-9", url: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=60", altText: "Clear cache options configuration screen", sortOrder: 0 }
    ]
  },
  {
    id: "ext-10",
    slug: "session-buddy-tab-manager",
    chromeStoreId: "sessionbuddy-id",
    name: "Session Buddy: Tab Manager",
    tagline: "A unified tab explorer and session manager. Save open tabs and restore them.",
    description: "A clean, fast session manager for power users. It allows developers to save groups of open browser tabs as custom sessions, search through active tabs across windows, and recover tabs after system crashes. Great for organizing documentation tabs during project switches.",
    logoUrl: "🗂️",
    websiteUrl: "https://sessionbuddy.com",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "approved",
    isFeatured: false,
    isSponsored: false,
    categoryId: "productivity",
    categorySlug: "productivity",
    categoryName: "Productivity",
    version: "4.0.2",
    totalUsers: 1500000,
    weeklyUsers: 250000,
    avgRating: 4.82,
    totalReviews: 4500,
    totalInstalls: 680000,
    clickCount: 8100,
    metaTitle: "Session Buddy Tab Manager - Save browser tabs",
    metaDescription: "Consolidate your open pages, save stack traces, and recover window sessions cleanly.",
    tags: ["Tabs", "Productivity", "Session Manager", "Tab Saver"],
    permissions: ["tabs", "sessions", "storage"],
    pricingType: "free",
    trustBadge: "Editor Approved",
    createdAt: "2016-08-20T00:00:00Z",
    updatedAt: "2026-05-10T00:00:00Z",
    screenshots: [
      { id: "s10-1", extensionId: "ext-10", url: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop&q=60", altText: "Session Buddy dashboard organizing tab list", sortOrder: 0 }
    ]
  },
  {
    id: "ext-11",
    slug: "github-copilot",
    chromeStoreId: "github-copilot-id",
    name: "GitHub Copilot",
    tagline: "Your AI pair programmer. Get autocomplete-style suggestions and chat help as you write code.",
    description: "GitHub Copilot is the world's most widely adopted AI developer tool. It provides autocomplete-style suggestions as you code, translates comments into executable code, and lets you chat with an AI assistant in your editor to solve problems, write tests, and understand complex legacy codebases.",
    logoUrl: "💻",
    websiteUrl: "https://github.com/features/copilot",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "featured",
    isFeatured: true,
    isSponsored: false,
    categoryId: "developer-tools",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    version: "1.254.0",
    totalUsers: 1500000,
    weeklyUsers: 400000,
    avgRating: 4.82,
    totalReviews: 12500,
    totalInstalls: 980000,
    clickCount: 25000,
    metaTitle: "GitHub Copilot - AI Pair Programmer Extension",
    metaDescription: "Get autocomplete-style suggestions, rewrite code, and chat with AI in your editor.",
    tags: ["AI", "Coding Assistant", "Developer Tools", "GitHub", "Autocomplete"],
    permissions: ["activeTab", "storage"],
    pricingType: "paid",
    price: 10.00,
    trustBadge: "Editor Approved",
    createdAt: "2022-06-21T00:00:00Z",
    updatedAt: "2026-06-05T00:00:00Z",
    screenshots: [
      { id: "s11-1", extensionId: "ext-11", url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=60", altText: "GitHub Copilot auto-completion suggestions in editor", sortOrder: 0 }
    ]
  },
  {
    id: "ext-12",
    slug: "codeium",
    chromeStoreId: "codeium-id",
    name: "Codeium",
    tagline: "Free AI code autocomplete and search. Accelerate your coding workflow with smart chat.",
    description: "Codeium is a free, ultra-fast alternative to GitHub Copilot. It offers single-line and multi-line code auto-completion in over 70 languages, inline chat instructions to refactor code, and repository-level context search to answer questions about your entire codebase.",
    logoUrl: "⚡",
    websiteUrl: "https://codeium.com",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "approved",
    isFeatured: true,
    isSponsored: false,
    categoryId: "developer-tools",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    version: "1.8.4",
    totalUsers: 600000,
    weeklyUsers: 120000,
    avgRating: 4.86,
    totalReviews: 2400,
    totalInstalls: 380000,
    clickCount: 14200,
    metaTitle: "Codeium - Free AI Code Autocomplete & Chat",
    metaDescription: "Ultra-fast free AI autocomplete, code search, and chat companion for developers.",
    tags: ["AI", "Coding Assistant", "Autocomplete", "Free AI", "Refactor"],
    permissions: ["activeTab", "storage"],
    pricingType: "freemium",
    price: 0.00,
    trustBadge: "Best Free Alternative",
    createdAt: "2023-01-10T00:00:00Z",
    updatedAt: "2026-06-03T00:00:00Z",
    screenshots: [
      { id: "s12-1", extensionId: "ext-12", url: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=800&auto=format&fit=crop&q=60", altText: "Codeium inline suggestions panel", sortOrder: 0 }
    ]
  },
  {
    id: "ext-13",
    slug: "continue-dev",
    chromeStoreId: "continue-id",
    name: "Continue.dev",
    tagline: "The open-source AI code assistant. Easily connect any LLM to your IDE.",
    description: "Continue is the leading open-source AI code assistant. It allows you to build custom software development sidecars by connecting local LLMs (like Ollama, Llama3) or API-based models (like GPT-4, Claude) for code autocomplete, inline refactoring, and code understanding.",
    logoUrl: "🔄",
    websiteUrl: "https://continue.dev",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "approved",
    isFeatured: false,
    isSponsored: false,
    categoryId: "developer-tools",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    version: "0.8.30",
    totalUsers: 250000,
    weeklyUsers: 65000,
    avgRating: 4.89,
    totalReviews: 1100,
    totalInstalls: 180000,
    clickCount: 9800,
    metaTitle: "Continue.dev - Open Source AI Code Assistant",
    metaDescription: "Connect any LLM to your editor for free code auto-completion and chat.",
    tags: ["Open Source", "AI", "Ollama", "Local LLM", "Coding Assistant"],
    permissions: ["activeTab", "storage"],
    pricingType: "free",
    trustBadge: "Best Open Source",
    createdAt: "2023-08-15T00:00:00Z",
    updatedAt: "2026-05-20T00:00:00Z",
    screenshots: [
      { id: "s13-1", extensionId: "ext-13", url: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=800&auto=format&fit=crop&q=60", altText: "Continue.dev sidebar custom LLM connection settings", sortOrder: 0 }
    ]
  },
  {
    id: "ext-14",
    slug: "tabnine",
    chromeStoreId: "tabnine-id",
    name: "Tabnine",
    tagline: "Enterprise-grade AI code assistant. Secure, private, and trained on permissive code.",
    description: "Tabnine is the pioneer in AI code completion, focusing on security and compliance. It offers private AI models that can be run on-premise or in your cloud, ensuring your source code never leaves your secure environment. Perfect for enterprise teams.",
    logoUrl: "🧩",
    websiteUrl: "https://tabnine.com",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "approved",
    isFeatured: false,
    isSponsored: false,
    categoryId: "developer-tools",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    version: "5.0.32",
    totalUsers: 1000000,
    weeklyUsers: 180000,
    avgRating: 4.62,
    totalReviews: 3100,
    totalInstalls: 700000,
    clickCount: 7800,
    metaTitle: "Tabnine - Enterprise AI Code Completion & Assistant",
    metaDescription: "Secure and private AI coding assistant. Permissive-only models for safe enterprise coding.",
    tags: ["AI", "Enterprise", "Privacy", "Coding Assistant", "Security"],
    permissions: ["activeTab", "storage"],
    pricingType: "freemium",
    price: 12.00,
    trustBadge: "Most Secure",
    createdAt: "2018-11-04T00:00:00Z",
    updatedAt: "2026-05-18T00:00:00Z",
    screenshots: [
      { id: "s14-1", extensionId: "ext-14", url: "https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=800&auto=format&fit=crop&q=60", altText: "Tabnine private model editor interface", sortOrder: 0 }
    ]
  },
  {
    id: "ext-15",
    slug: "blackbox-ai",
    chromeStoreId: "blackbox-id",
    name: "Blackbox AI",
    tagline: "Superfast AI code search and auto-completion. Turn questions into code instantly.",
    description: "Blackbox AI is built to search millions of repositories for code snippets. It provides autocomplete suggestions in your editor and can extract code from videos and images instantly. Fast, versatile, and highly reliable for copying and finding scripts.",
    logoUrl: "⬛",
    websiteUrl: "https://useblackbox.io",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "approved",
    isFeatured: false,
    isSponsored: false,
    categoryId: "developer-tools",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    version: "2.9.1",
    totalUsers: 800000,
    weeklyUsers: 140000,
    avgRating: 4.71,
    totalReviews: 1800,
    totalInstalls: 490000,
    clickCount: 11000,
    metaTitle: "Blackbox AI - Code Search and Autocomplete",
    metaDescription: "Instant code search, video code extraction, and ultra-fast AI autocomplete for developers.",
    tags: ["AI Search", "Coding Assistant", "Video OCR", "Python", "Javascript"],
    permissions: ["activeTab", "storage"],
    pricingType: "freemium",
    price: 9.99,
    trustBadge: "Best For Code Search",
    createdAt: "2021-05-12T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
    screenshots: [
      { id: "s15-1", extensionId: "ext-15", url: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=60", altText: "Blackbox AI code search console", sortOrder: 0 }
    ]
  },
  {
    id: "ext-16",
    slug: "codegeex",
    chromeStoreId: "codegeex-id",
    name: "CodeGeeX",
    tagline: "Open-source multilingual AI coding assistant. Translate code across programming languages.",
    description: "CodeGeeX is a powerful multilingual AI coding assistant. Beyond writing boilerplate codes and explanation, it specializes in high-fidelity translation of code blocks from one programming language to another (e.g., Python to Go). Supporting multiple LLMs, it speeds up cross-platform transitions.",
    logoUrl: "🐲",
    websiteUrl: "https://codegeex.cn",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "approved",
    isFeatured: false,
    isSponsored: false,
    categoryId: "developer-tools",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    version: "2.10.0",
    totalUsers: 400000,
    weeklyUsers: 75000,
    avgRating: 4.76,
    totalReviews: 950,
    totalInstalls: 250000,
    clickCount: 6200,
    metaTitle: "CodeGeeX - Multilingual AI Coding Assistant",
    metaDescription: "AI code generator, translator, and explainer. Translate code easily between 20+ languages.",
    tags: ["AI", "Code Translation", "Multilingual", "Coding Assistant", "Free AI"],
    permissions: ["activeTab", "storage"],
    pricingType: "free",
    trustBadge: "Best Code Translator",
    createdAt: "2022-09-01T00:00:00Z",
    updatedAt: "2026-05-15T00:00:00Z",
    screenshots: [
      { id: "s16-1", extensionId: "ext-16", url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=60", altText: "CodeGeeX code translation dashboard", sortOrder: 0 }
    ]
  },
  {
    id: "ext-17",
    slug: "scispace",
    chromeStoreId: "scispace-id",
    name: "SciSpace Copilot",
    tagline: "Your AI research assistant. Explain papers, search literature, and analyze equations.",
    description: "SciSpace Copilot is a powerful browser helper for researchers and students. It highlights complex texts, summarizes scientific papers, explains difficult jargon, and breaks down complex mathematical equations or data tables in real-time. Instantly search a database of over 200 million research papers.",
    logoUrl: "🧬",
    websiteUrl: "https://typeset.io",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "approved",
    isFeatured: true,
    isSponsored: false,
    categoryId: "research-learning",
    categorySlug: "research-learning",
    categoryName: "Research & Learning",
    version: "2.3.1",
    totalUsers: 800000,
    weeklyUsers: 150000,
    avgRating: 4.84,
    totalReviews: 1850,
    totalInstalls: 540000,
    clickCount: 12500,
    metaTitle: "SciSpace Copilot - AI Research Assistant",
    metaDescription: "Explain scientific papers, analyze equations, and search academic literature.",
    tags: ["Research", "AI Assistant", "Science", "Literature", "Study"],
    permissions: ["activeTab", "storage"],
    pricingType: "freemium",
    price: 12.00,
    trustBadge: "Best For Sci Papers",
    createdAt: "2023-03-14T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
    screenshots: [
      { id: "s17-1", extensionId: "ext-17", url: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&auto=format&fit=crop&q=60", altText: "SciSpace dashboard explaining a research journal", sortOrder: 0 }
    ]
  },
  {
    id: "ext-18",
    slug: "explainpaper",
    chromeStoreId: "explainpaper-id",
    name: "Explainpaper",
    tagline: "Upload complex research papers and get simple, easy-to-understand explanations.",
    description: "Explainpaper is the easiest way to read academic papers. Simply highlight a confusing passage or equation, and Explainpaper's AI will translate it into plain English. It helps students, engineers, and researchers digest dense articles 10x faster.",
    logoUrl: "📄",
    websiteUrl: "https://explainpaper.com",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "approved",
    isFeatured: false,
    isSponsored: false,
    categoryId: "research-learning",
    categorySlug: "research-learning",
    categoryName: "Research & Learning",
    version: "1.4.0",
    totalUsers: 300000,
    weeklyUsers: 72000,
    avgRating: 4.76,
    totalReviews: 680,
    totalInstalls: 210000,
    clickCount: 7400,
    metaTitle: "Explainpaper - Simple Explanations for Academic Papers",
    metaDescription: "Highlight difficult paper sections and get plain explanations instantly.",
    tags: ["Explain Paper", "Study Helper", "AI", "Reading Assistant"],
    permissions: ["activeTab", "storage"],
    pricingType: "freemium",
    price: 7.99,
    trustBadge: "Easiest to Use",
    createdAt: "2023-10-18T00:00:00Z",
    updatedAt: "2026-05-12T00:00:00Z",
    screenshots: [
      { id: "s18-1", extensionId: "ext-18", url: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&auto=format&fit=crop&q=60", altText: "Explainpaper highlighting text and showing simple explanation", sortOrder: 0 }
    ]
  },
  {
    id: "ext-19",
    slug: "scholarcy",
    chromeStoreId: "scholarcy-id",
    name: "Scholarcy: Research Paper Summarizer",
    tagline: "Read research papers faster. Summarize articles and compile flashcards in seconds.",
    description: "Scholarcy is an interactive library and summary tool. It reads academic papers, book chapters, and reports, extracting key facts, figures, and bibliographies. It creates structured summary flashcards to help researchers, students, and analysts quickly evaluate articles.",
    logoUrl: "🎓",
    websiteUrl: "https://scholarcy.com",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "approved",
    isFeatured: false,
    isSponsored: false,
    categoryId: "research-learning",
    categorySlug: "research-learning",
    categoryName: "Research & Learning",
    version: "3.2.1",
    totalUsers: 450000,
    weeklyUsers: 95000,
    avgRating: 4.72,
    totalReviews: 980,
    totalInstalls: 310000,
    clickCount: 9100,
    metaTitle: "Scholarcy - Research Paper Summarizer Extension",
    metaDescription: "Generate structured flashcards, summary sheets, and reference exports from articles.",
    tags: ["Summary", "Study Tools", "Literature Review", "Flashcards"],
    permissions: ["activeTab", "storage"],
    pricingType: "freemium",
    price: 9.99,
    trustBadge: "Best Summarizer",
    createdAt: "2021-11-20T00:00:00Z",
    updatedAt: "2026-04-10T00:00:00Z",
    screenshots: [
      { id: "s19-1", extensionId: "ext-19", url: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&auto=format&fit=crop&q=60", altText: "Scholarcy compiling paper flashcards summary", sortOrder: 0 }
    ]
  },
  {
    id: "ext-20",
    slug: "webchatgpt",
    chromeStoreId: "webchatgpt-id",
    name: "WebChatGPT: ChatGPT with Internet Access",
    tagline: "Augment your ChatGPT prompts with relevant web search results for accurate answers.",
    description: "WebChatGPT is a browser extension that adds relevant web search results to your prompts on ChatGPT. By providing up-to-date internet access, it reduces hallucinations and helps researchers obtain highly accurate, cited, and recent information for their studies.",
    logoUrl: "🌐",
    websiteUrl: "https://webchatgpt.app",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "approved",
    isFeatured: true,
    isSponsored: false,
    categoryId: "research-learning",
    categorySlug: "research-learning",
    categoryName: "Research & Learning",
    version: "4.1.8",
    totalUsers: 1200000,
    weeklyUsers: 220000,
    avgRating: 4.79,
    totalReviews: 3900,
    totalInstalls: 850000,
    clickCount: 18900,
    metaTitle: "WebChatGPT - Give ChatGPT Access to Internet",
    metaDescription: "Get real-time web search results and source citation links inside ChatGPT prompts.",
    tags: ["ChatGPT", "Web Search", "Real-Time AI", "Study Helper"],
    permissions: ["activeTab", "storage"],
    pricingType: "free",
    trustBadge: "Student Favorite",
    createdAt: "2022-12-15T00:00:00Z",
    updatedAt: "2026-06-02T00:00:00Z",
    screenshots: [
      { id: "s20-1", extensionId: "ext-20", url: "https://images.unsplash.com/photo-1546074177-ffedd79d424c?w=800&auto=format&fit=crop&q=60", altText: "WebChatGPT search queries toggle inside ChatGPT screen", sortOrder: 0 }
    ]
  },
  {
    id: "ext-21",
    slug: "youtube-summary-glarity",
    chromeStoreId: "youtube-summary-id",
    name: "YouTube Summary with ChatGPT",
    tagline: "Get instant, structured summaries and transcripts for YouTube videos using AI.",
    description: "YouTube Summary uses ChatGPT to generate high-fidelity transcripts and summaries of YouTube lectures, webinars, and tutorials. It saves students hours of video watching by highlighting core concepts, action items, and timestamps instantly.",
    logoUrl: "📺",
    websiteUrl: "https://glarity.app",
    chromeStoreUrl: "https://chromewebstore.google.com",
    status: "approved",
    isFeatured: false,
    isSponsored: false,
    categoryId: "research-learning",
    categorySlug: "research-learning",
    categoryName: "Research & Learning",
    version: "3.8.4",
    totalUsers: 950000,
    weeklyUsers: 160000,
    avgRating: 4.81,
    totalReviews: 2400,
    totalInstalls: 620000,
    clickCount: 13500,
    metaTitle: "YouTube Summary with ChatGPT - Get Video Transcripts",
    metaDescription: "Summarize long videos, lectures, and tutorials with ChatGPT. Access timestamps instantly.",
    tags: ["YouTube Summary", "Video OCR", "Study Tools", "Lecture Notes"],
    permissions: ["activeTab", "storage"],
    pricingType: "free",
    trustBadge: "Best Video Summarizer",
    createdAt: "2023-02-18T00:00:00Z",
    updatedAt: "2026-05-28T00:00:00Z",
    screenshots: [
      { id: "s21-1", extensionId: "ext-21", url: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&auto=format&fit=crop&q=60", altText: "YouTube Summary transcription side panel on YouTube video", sortOrder: 0 }
    ]
  }
];

export const mockReviews: Record<string, Review[]> = {
  "ext-1": [
    {
      id: "r1-1",
      extensionId: "ext-1",
      userId: "u-1",
      userName: "Alex Rivers",
      userAvatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=60",
      rating: 5,
      title: "Essential for my daily developer workflow",
      body: "Having ChatGPT and Claude right in my side panel saves me from switching tabs 50 times a day. The file uploader handles my code exports flawlessly. Absolutely worth the upgrade.",
      pros: ["Double AI models (Claude + ChatGPT)", "Excellent side-panel integration", "Smooth file parser"],
      cons: ["Needs API key for custom models in free version"],
      verified: true,
      helpfulVotes: 24,
      status: "approved",
      createdAt: "2026-05-22T12:00:00Z",
      updatedAt: "2026-05-22T12:00:00Z"
    },
    {
      id: "r1-2",
      extensionId: "ext-1",
      userId: "u-2",
      userName: "Siti Rahma",
      userAvatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=60",
      rating: 4,
      title: "Extremely fast, but needs better history sync",
      body: "I love the UI and OCR parser. However, my chat history sometimes fails to sync when I switch browsers. Highly recommend nonetheless.",
      pros: ["Quick shortcuts", "OCR works perfectly"],
      cons: ["History sync issues"],
      verified: false,
      helpfulVotes: 7,
      status: "approved",
      createdAt: "2026-05-18T10:30:00Z",
      updatedAt: "2026-05-18T10:30:00Z"
    }
  ],
  "ext-2": [
    {
      id: "r2-1",
      extensionId: "ext-2",
      userId: "u-3",
      userName: "John Miller",
      userAvatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=60",
      rating: 5,
      title: "Indispensable writing tool",
      body: "Grammarly is running everywhere in my browser. The tone checker is a lifesaver for professional emails. The pricing is steep, but the utility is unparalleled.",
      pros: ["Best-in-class correction", "Polishes tone", "Works in almost all web text boxes"],
      cons: ["Expensive monthly tier"],
      verified: true,
      helpfulVotes: 42,
      status: "approved",
      createdAt: "2026-06-02T14:20:00Z",
      updatedAt: "2026-06-02T14:20:00Z"
    }
  ]
};

import { SourceCodeProduct } from "@/types/source-code";

export interface MockBlogPost {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  coverImageUrl: string;
  category: string;
  tags: string[];
  readingTimeMinutes: number;
  publishedAt: string;
  isFeatured?: boolean;
  relatedExtensionIds?: string[];
  relatedSourceCodeIds?: string[];
}

export const mockBlogPosts: MockBlogPost[] = [
  {
    id: "post-1",
    slug: "how-to-build-rt-rw-management-app",
    title: "How To Build an RT/RW Management App",
    excerpt: "Learn how to build a complete neighborhood management portal using Next.js and Supabase.",
    content: "Building management platforms for local communities requires careful planning of authentication, role systems (admin, citizen), and message broadcasting. In this tutorial, we will walk you through setting up a neighborhood management system step-by-step. We'll implement user invitation codes, finance tracking panels, and automated WhatsApp alert integrations...",
    coverImageUrl: "https://images.unsplash.com/photo-1546074177-ffedd79d424c?w=1200&auto=format&fit=crop&q=80",
    category: "Tutorials",
    tags: ["Tutorials", "Next.js", "Laravel"],
    readingTimeMinutes: 8,
    publishedAt: "2026-06-05T08:00:00Z",
    isFeatured: true,
    relatedSourceCodeIds: ["sc-1"]
  },
  {
    id: "post-2",
    slug: "nextjs-authentication-guide",
    title: "Next.js Authentication Guide",
    excerpt: "Step-by-step tutorial implementing secure OAuth and magic links using Supabase Auth.",
    content: "Secure user sessions are the baseline of any modern SaaS project. In this guide, we walk through setting up Next.js 16 with Supabase Auth, using cookies to synchronize sessions. We cover magic links, Google logins, middleware route protections, and managing auth states on the client side smoothly...",
    coverImageUrl: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1200&auto=format&fit=crop&q=80",
    category: "Tutorials",
    tags: ["Tutorials", "Next.js", "SaaS"],
    readingTimeMinutes: 5,
    publishedAt: "2026-06-03T10:00:00Z",
    relatedSourceCodeIds: ["sc-2"]
  },
  {
    id: "post-3",
    slug: "chrome-extension-development-basics",
    title: "Chrome Extension Development Basics",
    excerpt: "Learn how to build your first browser popup utility using manifest V3 guidelines.",
    content: "Ever wanted to build your own sidebar or content modifier? Getting started with Chrome extension development is straightforward if you understand the boundary roles of manifest.json, background service workers, content scripts, and side-panel APIs. In this guide, we build a simple translator popup using local translation APIs...",
    coverImageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80",
    category: "Tutorials",
    tags: ["Tutorials", "Developer Tools", "Guides"],
    readingTimeMinutes: 6,
    publishedAt: "2026-06-01T11:00:00Z",
    relatedExtensionIds: ["ext-1"]
  },
  {
    id: "post-4",
    slug: "case-study-ublock-origin-memory",
    title: "Case Study: How uBlock Origin Optimizes Memory Overhead",
    excerpt: "An architectural review of how uBlock Origin keeps memory usage low while blocking millions of tracker scripts.",
    content: "Blocking ads is simple, but doing it without rendering your browser unusable is a significant technical challenge. uBlock Origin utilizes highly optimized structures for matching domain lists, avoiding high-overhead regex engines in favor of simple lookup tables. In this case study, we examine how it manages memory pages...",
    coverImageUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200&auto=format&fit=crop&q=80",
    category: "Case Studies",
    tags: ["Case Studies", "Adblock", "Security"],
    readingTimeMinutes: 9,
    publishedAt: "2026-05-28T09:00:00Z",
    relatedExtensionIds: ["ext-5"]
  },
  {
    id: "post-5",
    slug: "review-languagetool-vs-grammarly",
    title: "Detailed Review: LanguageTool vs Grammarly in 2026",
    excerpt: "We compare the two giants of writing assistant extensions: open-source LanguageTool vs enterprise-grade Grammarly.",
    content: "Whether you are editing academic papers or drafting client proposals, having an automated second eye is indispensable. While Grammarly has pioneered generative AI writing prompts, LanguageTool has doubled down on multilingual grammar correction and strict offline privacy guarantees. This review compares their features side-by-side...",
    coverImageUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=1200&auto=format&fit=crop&q=80",
    category: "Reviews",
    tags: ["Reviews", "Writing", "AI Tools"],
    readingTimeMinutes: 7,
    publishedAt: "2026-05-25T14:30:00Z",
    relatedExtensionIds: ["ext-3", "ext-2"]
  },
  {
    id: "post-6",
    slug: "manifest-v3-migration-guide",
    title: "Manifest V3 Migration Guide: Web Request to Declarative Net Request",
    excerpt: "A developer manual on migration rules, declarative rulesets, and permission changes for Chrome Extensions.",
    content: "Google Chrome's transition from Manifest V2 to V3 has introduced breaking changes, especially for privacy extensions that block network requests. Replacing the dynamic webRequest API with declarativeNetRequest requires developers to pre-define rulesets instead of intercepting headers on the fly. This guide details ruleset optimization...",
    coverImageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80",
    category: "Development Guides",
    tags: ["Development Guides", "Developer Tools", "Manifest V3"],
    readingTimeMinutes: 10,
    publishedAt: "2026-05-20T10:00:00Z",
    relatedExtensionIds: ["ext-6"]
  }
];

export const mockSourceCodes: SourceCodeProduct[] = [
  {
    id: "sc-1",
    slug: "rtrw-management-system",
    name: "RT/RW Management System",
    tagline: "Neighborhood portal featuring billing tracking, citizen data logs, and announcement boards.",
    description: "A complete, production-ready neighborhood portal system. Admin dashboard lets RT/RW coordinators upload monthly payment records, verify citizen list details, and broadcast notifications. Built with high security defaults.",
    techStack: ["Next.js", "Supabase", "Tailwind"],
    price: "Rp99.000",
    priceRaw: 99000,
    thumbnail: "🏢",
    screenshots: [
      "https://images.unsplash.com/photo-1546074177-ffedd79d424c?w=800&auto=format&fit=crop&q=60"
    ],
    demoLink: "https://demo.rtrwportal.com",
    category: "Fullstack"
  },
  {
    id: "sc-2",
    slug: "ai-blog-platform",
    name: "AI Blog Platform",
    tagline: "Generate, outline, and schedule content dynamically using OpenAI integration inside a Markdown editor.",
    description: "Write content twice as fast. AI Blog Platform connects ChatGPT outline tools directly to your draft publisher. Supports automatic tags recommendations, SEO score checklists, and dynamic page indexing.",
    techStack: ["Next.js", "PostgreSQL", "Tailwind"],
    price: "Rp79.000",
    priceRaw: 79000,
    thumbnail: "🤖",
    screenshots: [
      "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=60"
    ],
    demoLink: "https://demo.aiblogwriter.com",
    category: "SaaS"
  },
  {
    id: "sc-3",
    slug: "portfolio-pro-template",
    name: "Portfolio Pro Template",
    tagline: "Minimalist, extremely fast portfolio template with high contrast developer showcases.",
    description: "Stunning developer landing page template. Clean grid sections highlighting open source project repos, blog summaries, and contact fields. Fully responsive and ready for Vercel deployment in 1-click.",
    techStack: ["React", "Tailwind", "Framer Motion"],
    price: "Rp59.000",
    priceRaw: 59000,
    thumbnail: "🎨",
    screenshots: [
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=60"
    ],
    demoLink: "https://demo.portfoliopro.com",
    category: "Templates"
  },
  {
    id: "sc-4",
    slug: "pos-management-system",
    name: "POS Management System",
    tagline: "Cashier portal system supporting inventory, receipts invoice printer sync, and sales charts.",
    description: "High performance Point-of-Sale management layout. Cashier console manages billing checklists, automatic barcode matching, and outputs sales analytics records dynamically. Ready for local store implementation.",
    techStack: ["Laravel", "MySQL", "Bootstrap"],
    price: "Rp99.000",
    priceRaw: 99000,
    thumbnail: "📊",
    screenshots: [
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=60"
    ],
    demoLink: "https://demo.possystem.com",
    category: "Fullstack"
  }
];
